// <auto-generated />
namespace ControleEstoqueComEF6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class versao02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(versao02));
        
        string IMigrationMetadata.Id
        {
            get { return "202108082110003_versao02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
